### ISSUE TITLE
【フォーム作成】ユーザーが２つ以上ポートフォリオを作成している場合

### ISSUE THREAD

**Issue by subaru-hello** [hiyoco-connect/hiyoco-connect#33]
## 概要
ユーザーがポートフォリオを２つ以上作成している場合、Profile作成画面の表示方法をどのようにするか考え、既存のProfile作成formを改善する。

### TODO

- [ ] ポートフォリオが二つ以上の場合のProfile登録方法を考える
選択肢
　　■フォームを自動で増やす
　　■それとも３つまでの登録にする
　　■またはポートフォリオの作成は別の画面で行うか

**Comment by mayu-tateno** [comment]
## フォームを増やしていく実装方法
gem 'cocoon'を使用する方法が良いかも
[cocoonのGitHub](https://github.com/nathanvda/cocoon)

これを使用しない場合だとjQueryなどで実装していくことになるが、記述量も多く時間がよりかかりそう。
[参考: 【Rails】JavaScriptでフォームを追加する方法](https://qiita.com/koki_73/items/22247b5d49eab56ec158)
※どちらにせよjQueryの導入は必要。
