### ISSUE TITLE
 ポートフォリオの入力欄が消えてしまう

### ISSUE THREAD

**Issue by subaru-hello** [hiyoco-connect/hiyoco-connect#35]
プロフィールの作成時にバリデーションエラーが発生すると、ポートフォリオの入力欄が消えてしまう

【再現手順】
1.「ポートフォリオ名が未入力」かつ「他の必須項目が未入力」でプロフィールを作成ボタンを押下する
2. バリデーションエラーとなり、newページのrenderが発生する
3. ポートフォリオの入力欄が消えてしまう
![image](https://user-images.githubusercontent.com/84756197/154790388-7a6b59f0-d391-420d-9709-d7134e99025e.png)

**Comment by mayu-tateno** [comment]
## 解決方法
おそらく
```
<%= f.fields_for :portfolios do |portfolio_form| %>
```
を
```
 <%= f.fields_for :portfolios, @profile.portfolios.build do |portfolio_form| %>
```
に変更すればこのエラーは解消できる。
[参考](https://acchann.hatenablog.com/entry/2018/03/16/224300)
![localhost_3000_profiles (4)](https://user-images.githubusercontent.com/87419889/154950119-e381d122-31a7-4793-bba9-07dfc855e35d.png)

**Comment by mayu-tateno** [comment]
@profile.portfolios.buildがある場合のHTML
```html
<input type="hidden" name="profile[portfolios_attributes][0][profile_id]" id="profile_portfolios_attributes_0_profile_id">
```

**Comment by mayu-tateno** [comment]
## 新規作成失敗時に入力欄が消える理由(推測)
あくまで推測ですが・・こんな感じかなという考えを貼ります

新規作成失敗時、ルーティング(というかURL)は/profilesのcreateのままrender :newでnewページがレンダリング(描画のみ)されます。
newアクション発火時にbuildしていた`@profile`と`@portfolio`は、createアクションが発火し、作成失敗した時点で保存されず破棄されたのと同じ状態になっているのではないかと思います。
この時createアクション内では
```ruby
@profile = current_user.build_profile(profile_params)
```
で`@profile`はbuildされているので作成失敗してもそのまま情報が残っている
(作成失敗してもフォーム内に入力内容が残っていることからもわかる)
potfolioの情報はprofile_params内のportfolios_attributesに格納されることになるが、未入力の場合はここの情報はnill。その上`@portfolio`もbuildされていない。
(※そもそもポートフォリオ名が未入力だった場合はポートフォリオとして保存されない設定にしているし、名前を入力している場合はprofile_paramsに情報が残る？)
`@potfolio`が存在しないので`@portfolio`をフォームに受け渡せないために表示できない？
だからfields_forに引数として`@profile.portfolios.build`を渡す必要がある？

(edit, updateアクションの場合は新しくbuildしたものがフォームに渡ってしまうと、既存のportfolioのidを取得できないので新規作成と同じことになってしまう)

しかし作成失敗時フォーム自体が表示されない理由にはなってないっぽい・・・
form_withやfields_forでは扱うモデルクラスのインスタンスを渡さなければ表示されない仕様なのだとしたら説明はつくが

## 解決策
もしこの仮説が正しければ、
```ruby
  def create
    @profile = current_user.build_profile(profile_params)

    # ココ追加
    @profile.portfolios.build if @profile.portfolios.blank?

    if @profile.save
      redirect_to @profile, success: t('defaults.messages.created', item: Profile.model_name.human)
    else
      flash.now['danger'] = t('defaults.messages.not_created', item: Profile.model_name.human)
      render :new
    end
  end
```
こんな感じでcreateアクション内で、`@profile`をbuildした後にprofile.portfoliosが無ければ、再度buildのような感じで行けるかも。
試してみないと分からないですが...

解決策 By 山本さん

## 補足
上記の方法を中野さんが試し編集・更新に成功！！

この方法だと、フロントでインスタンス変数をbuildして渡していたのを、コントローラーのアクション内(バックエンド)でインスタンス変数を作ることができるので好ましい。
ついでに、`_form.html.erb`に変更を加えなくても使いまわせる。
