### ISSUE TITLE
プロフィールを未作成でマイページボタンを押すとエラーになる

### ISSUE THREAD

**Issue by shota-hope** [hiyoco-connect/hiyoco-connect#74]
- プロフィール未作成の場合、プロフィール作成ページに遷移すること
- リンクの文言は「マイページ」→「マイプロフィール」
- [#71](https://github.com/hiyoco-connect/hiyoco-connect/pull/71#discussion_r819316665)のコメント対応

**Comment by kohei-yamamoto1012** [comment]
プロフィール未作成の場合、プロフィール作成ページに遷移すること

**Comment by subaru-hello** [comment]
こちら対応します！

**Comment by kohei-yamamoto1012** [comment]
- [feat: ヘッダーにマイページ,プロフィール一覧を追加 #59 ](https://github.com/hiyoco-connect/hiyoco-connect/pull/71)の漏れです。

- 追加で、リンクの文言は「マイページ」ではなく、「マイプロフィール」です。

**Comment by shota-hope** [comment]
コメント、対応、ありがとうございます！
あとヘッダーリンク追加のプルリクにコメントしたのですが、現状の記述だとおそらくエラーになるので併せてご対応お願いできますでしょうか！
https://github.com/hiyoco-connect/hiyoco-connect/pull/71#discussion_r819316665

**Comment by kohei-yamamoto1012** [comment]
- プロフィール未作成の場合、プロフィール作成ページに遷移すること
- リンクの文言は「マイページ」→「マイプロフィール」
- [#71](https://github.com/hiyoco-connect/hiyoco-connect/pull/71#discussion_r819316665)のコメント対応
