### ISSUE TITLE
開発環境・本番環境の両方でGit Hub認証を機能させる

### ISSUE THREAD

**Issue by kohei-yamamoto1012** [hiyoco-connect/hiyoco-connect#75]
- 現状、GitHub認証のドメイン設定が`http://localhost:3000`に設定されているため、本番環境下でログインが行えない。
- hiyoco-connect organaizationのOAuth Appに開発・本番両方のドメインを登録する
- herokuに`master.key`を適用

**Comment by shota-hope** [comment]
credentials.yml.encに記載する際、本番環境用は
```production_key: ○○``` 
と記載する。
