### ISSUE TITLE
ユーザーがprofile未作成時にprofile_path(current_user.profile.id)でidがnilの為にエラーが出る

### ISSUE THREAD

**Issue by mayu-tateno** [hiyoco-connect/hiyoco-connect#84]
## 概要
ログイン時ユーザーがプロフィール未作成の場合、ヘッダーの「プロフィール作成」のリンクをクリックすると以下のようなエラーが発生する。
![image](https://user-images.githubusercontent.com/87419889/157435841-dc005032-cdb6-41d4-8024-899558a571b5.png)

条件分岐のelse節に従いプロフィール作成画面に遷移させたいのに、if節のパスの記述でエラーが発生している。

### 原因の絞り込み
ユーザーが**プロフィール作成済み**の場合は**正常**に動作することを確認済。

エラー画面のコンソールで、current_userの情報は正確に取得できた。
current_user.profileを打つとuser_idはcurrent_userのidが表示されたが、それ以外はnil。enumはデフォルト値。
つまり、profile_idはnilだった。
※プロフィール未作成なので当たり前ではあるが念の為検証結果を記載。

現在、ヘッダーの問題があると思われるコードは以下の通り。
```html
<%if current_user.profile.present?%>
  <li class="nav-item">
    <%= link_to (t 'defaults.myprofile'), profile_path(current_user.profile.id), class: "nav-link active text-dark" %>
  </li>
<%else%>
  <li class="nav-item">
    <%= link_to (t 'defaults.profile_new'), new_profile_path, class: "nav-link active text-dark"%>
  </li>
<%end%>
```
`profile_path(current_user.profile.id)`をたとえば`profiles_path`などに変更すると、
ユーザーがプロフィール未作成の場合でも期待する通りに動作した(つまり、新規作成画面へ遷移できた)ことから、
`profile_path(current_user.profile.id)`の記述が問題であると推定できる。

### なぜエラーが発生しているかの仮説
Railsがビューファイルをレンダリングする際、リンク先のルーティングが存在しない場合エラーを発生させるようになっている。
if文で条件分岐を行い表示し分けるようになっているのに関わりなく、レンダリングする時点でビューファイル内に記述があるパス全てを対象に、それぞれのルーティングが存在するか判定してからレンダリングしているからではないか？

もしこれが正しい場合、ログイン時のヘッダーをさらに「プロフィール作成」と「マイプロフィール」と表示させるため２つ用意し、application.htmlでレンダリングする際に条件分岐をさせるのがまず思いつく方法…。
他にうまい方法はないか調査中。。

**Comment by kohei-yamamoto1012** [comment]
### エラー原因
どうやら、プロフィール作成ページ(/profiles/new)に移動したタイミングで、`current_user.profile.present? `の実行結果が`true`となるようです。

試しにエラー画面で、`current_user.profile`の値を確認してみると以下のようになっています。
<img width="915" alt="image" src="https://user-images.githubusercontent.com/84756197/157888028-8eb3dc36-e10d-451d-a152-a15f99ca54d0.png">

そのため、プロフィール作成ページ上では` <%if current_user.profile.present? %>`の条件分岐が`true`となり、`profile_path(current_user.profile.id)`のリンクを生成しようとするが、`current_user.profile.id`が`nil`のためエラーになっているようです。


### 解決方法
現状の条件分岐に「DB保存済みか？」の条件を追加してあげることでエラーは解決できそうです。
```ruby
<% if current_user.profile.present? && current_user.profile.persisted? %>
 ```

**Comment by mayu-tateno** [comment]
ありがとうございます！！！！
やっぱり山本さんすっげえな…！
なるほど！確かにコンソール上でcurrent_user.profileを打つと、profile自体が存在しないといった結果が返って来るわけではなかったので、そこ微妙に引っ掛かってたんですよね。
そっか、newアクションが発火した時点で@profile = current_user.build_profileでまだ保存はしていなくてもbuildされてるからtrueになるんですね。。(user_idだけ入っているわけだ！)

ちょっと考えればわかりそうで、わからなかったです笑
エラーに遭遇すると理解度深まりますね！
