### ISSUE TITLE
herokuのアイドルタイム対応

### ISSUE THREAD

**Issue by kohei-yamamoto1012** [hiyoco-connect/hiyoco-connect#90]
- heroku free dynoが30分間アクセスないと、アイドルタイムに突入するのを回避する
- free dynoには`1000時間 / 月` の制限もあったと思うので注意

**Comment by mayu-tateno** [comment]
## 講じた対策
とりあえず立野個人のアカウントにHerokuの権限を移し、Free Dynoに設定。
Heroku Suchedulerで10分おきにひよこコネクトのサイトにcurlコマンドを打つよう設定しスリープを回避している。
※Heroku Schedulerでは10分おきと１時間おき、１日おきしか選択できない。

## 他選択肢
深夜帯などアクセスがほぼない時間帯にはスリープ対策を行わないようにするには深夜帯にはリクエストを行わないように条件分岐を記述したスクリプトを用意し、それを10分おきに実行するという方法もあるようです。
[参考: [ruby/php] herokuの自動スリープを「時間を指定」して抑制する](https://qiita.com/yamapa/items/6d26f5cdfeec88b5c348)

また、無料枠でも使用できるネットワーク監視サービス[UptimeRobot](https://uptimerobot.com/)などを使う方法もあります。
こちらも良さそうです。

今のところ現在講じた対策でも事足りると考えています。
今後もスリープ対策のベターな方法を検討し、ぼちぼち対応していきます。
何か対策を変更した場合必ず連絡いたします！
