### ISSUE TITLE
開発者たちのプロフィール作成

### ISSUE THREAD

**Issue by kohei-yamamoto1012** [hiyoco-connect/hiyoco-connect#94]
- リリース用のデプロイが完了次第、開発者たちのプロフィールを作成する

**Comment by kohei-yamamoto1012** [comment]
やまもとDone
https://hiyoco-connect.herokuapp.com/profiles/4

**Comment by shota-hope** [comment]
おおのDONE
https://hiyoco-connect.herokuapp.com/profiles/3

**Comment by mayu-tateno** [comment]
たての(一応)Done!
https://hiyoco-connect.herokuapp.com/profiles/2
